import React from 'react';
import {MainMenu} from './MainMenu';

export class Main extends React.Component {

	render() {
		return (
			<main role="main">
				<div className="featured-first featured-light" id="how">
					<div className="site-wrapper">
						<header><h2>How we can help you</h2></header>
						<section>
							<div>
							<p><em>Vision 100 IT exists to help churches - particularly church IT volunteers and ministry staff - to use IT better.</em></p>
<p>You might be one of these examples</p>
</div>
<div>
<div className="church-leader text-block"><h3>Overwhelmed pastor.</h3><p>We get it. You're a church leader in the 21st Century, realising that you can't avoid being online any longer you've put together a fancy_church.blogspot.com page, but now you're wondering if no website is better than what you've got.. It's looking more and more like a sunk cost and it doesn't show up in google anyway. The effort to get something professional up and running just seems too much amidst the weekly sermons and pastoral care. Already an autogenerated Facebook page for your church appeared last June and you're regularly wishing your ministry leaders could remember to CC you into their team emails - but who actually has time to sort through these IT things?</p><p>That's where we come in.</p></div>
<div className="church-volunteer text-block"><h3>"Voluntold" victim.</h3><p>We've been there. You've been "asked" to put together a webpage for church because you're the youngest and most "savvy" member of the church. They meant it as a compliment, honestly. Your web dev experience extends to your MySpace page back in 2005 where you successfully copy-pasted some html code you found online, and now you've landed the job of dragging your church into the brave new world of Facebook, Instagram, Content Management and Responsive Design. Your pastor sent you a link to awesome_church.com and wants a site just like it. You've mucked around with wordpress but you're struggling to get the office admin to engage enough to keep it updated. You just wish you had a bit of support and some better tools.</p><p>That's where we come in.</p></div>
<div className="IT-guru text-block"><h3>Capable. Over it.</h3><p>You understand websites and servers and have managed to get something off the ground for church, but it's starting to cost you a bit too much and you're struggling to persuade the eldership that it's worth investing in a more rigorous approach to church IT. Currently your site's up-time solely depends on the computer you have in your spare room being permanently connected to the outside world, but you're moving house in a week and it'll be down until a port becomes available in your new local DSLAM. Could be months. Wouldn't it be great if all you had to worry about was keeping things up to date, rather than keeping it online as well?</p><p>That's where we come in.</p></div>
</div>
<div>
<p>Vision 100 IT offers a suite of tools, services and training to allow you to utilise IT as an effective tool for ministry. We work collaboratively with your staff or designated church member to develop a tailored website and package of tools to keep your newcomers informed and your ministry teams connected. We provide assistance and training in best practices for tools you already use, and are open to exploring ways to combine your current approach and applications into our ecosystem.</p>

<p>"That's great! But who are you?" we hear you ask.</p>
</div>
						</section>
					</div>
				</div>
				<div className="featured-second featured-dark" id="who">
					<div className="site-wrapper">
						<header><h2>Who are Vision 100 IT?</h2></header>
						<section>
							<p>Bold claims for a group that hasn’t introduced ourselves yet! Who are Vision 100 IT then?</p>
<p>We’re a team of passionate IT and web development engineers, ministry leaders and management professionals who voluntarily build, maintain, train and educate our clients in IT systems on the basis of years of collective knowledge gleaned from within the IT industry.</p>

<p>Vision 100 IT has now existed for over a decade, and has gradually built up a knowledge base of best practices and approaches for doing church IT <i>sustainably</i>. We are all about getting <em>and keeping</em> our clients on the web, in order to more effectively reach the lost and minister to the people in their congregations.</p>
<p>
<h3>Meet the team:</h3>
<ul>
<li>Christian de Kievit</li>

<li>Mikey Lynch</li>

<li>Jason Imms</li>

<li>Jonno Haines</li>

<li>Emile Hofsink</li>

<li>Andrew Gibb</li>

<li>Alan Reader</li>

<li>Chris Haines</li>
</ul>
</p>
						</section>
					</div>
				</div>
				<div className="featured-third featured-light" id="tools">
					<div className="site-wrapper">
						<header><h2>Tools + Philosophy</h2></header>
						<section>
							<p></p>
						</section>
					</div>
				</div>
				<div className="featured-fourth featured-dark" id="events">
					<div className="site-wrapper">
						<header><h2>Events + Training</h2></header>
						<section>
							<p></p>
						</section>
					</div>
				</div>
				<div className="featured-fifth featured-light" id="pricing">
					<div className="site-wrapper">
						<header><h2>Pricing</h2></header>
						<section>
							<p>So this is the link that we know you clicked on first, so we'll get it out of the way so you can head back to the top and read about what we're offering before you write us off.</p>
							<p>For our core features and services, we won't invoice you at all. Not in a "free tier" and send you five emails a day about how awesome "premium" is sort of way, but in a "We're really eager for you to get the most out of your IT for the good of the Gospel" sort of way. How does that sound?</p>
							<p>The rationale is this: <blockquote>We want to focus on providing you a methodology that will keep you engaged with your IT, rather than a service that you can set and forget. If giving our services to you for free achieves that goal, we'll do it.</blockquote></p>
							<p>We do have some <em>services</em> that will carry a cost, but we think that if you've got the right people on the ground, and spend some time in our documentation, you'll be fine without it.</p>
							<p>One of our <em>products</em> does carry a cost as well, and that is our registration payment system. The majority of that is managing paypal's costs so we've kept it as minimal as possible</p>
						</section>
					</div>
				</div>
				<div className="featured-sixth featured-dark" id="join">
					<div className="site-wrapper">
						<header><h2>Come on board</h2></header>
						<section>
							<p></p>
						</section>
					</div>
				</div>
			</main>
		);
	}
}
