import React from 'react';
import {MainMenu} from './MainMenu';

export class Main extends React.Component {

	render() {
		return (
			<main role="main">
				<div className="featured-first featured-light" id="how">
					<div className="site-wrapper site-wrapper-padding">
						<header hidden>
							<h2>How we can help you</h2>
						</header>
						<section>
							<div className="text-slab">
								<em>Sometimes all you need is a bit of direction.
									<br/>
									We want to meet you where you are and get you up and running as best as possible</em>
							</div>
							<p>Vision 100 IT exists to help churches - particularly church IT volunteers and ministry staff - to use IT better.</p>
							<div className="example">
								<div className="church-leader text-block-3">
									<h3>Overwhelmed pastor.</h3>
									<p>We get it. You're a church leader in the 21st Century, realising that you can't avoid being online any longer you've put together a fancy_church.blogspot.com page, but now you're wondering if no website is better than what you've got.. It's looking more and more like a sunk cost and it doesn't show up in google anyway. The effort to get something professional up and running just seems too much amidst the weekly sermons and pastoral care. Already an autogenerated Facebook page for your church appeared last June and you're regularly wishing your ministry leaders could remember to CC you into their team emails - but who actually has time to sort through these IT things?</p>
									<p>That's where we come in.</p>
								</div>
								<div className="church-volunteer text-block-3">
									<h3>"Voluntold" victim.</h3>
									<p>We've been there. You've been "asked" to put together a webpage for church because you're the youngest and most "savvy" member of the church. They meant it as a compliment, honestly. Your web dev experience extends to your MySpace page back in 2005 where you successfully copy-pasted some html code you found online, and now you've landed the job of dragging your church into the brave new world of Facebook, Instagram, Content Management and Responsive Design. Your pastor sent you a link to awesome_church.com and wants a site just like it. You've mucked around with wordpress but you're struggling to get the office admin to engage enough to keep it updated. You just wish you had a bit of support and some better tools.</p>
									<p>That's where we come in.</p>
								</div>
								<div className="IT-guru text-block-3">
									<h3>Capable. Over it.</h3>
									<p>You understand websites and servers and have managed to get something off the ground for church, but it's starting to cost you a bit too much and you're struggling to persuade the eldership that it's worth investing in a more rigorous approach to church IT. Currently your site's up-time solely depends on the computer you have in your spare room being permanently connected to the outside world, but you're moving house in a week and it'll be down until a port becomes available in your new local DSLAM. Could be months. Wouldn't it be great if all you had to worry about was keeping things up to date, rather than keeping it online as well?</p>
									<p>That's where we come in.</p>
								</div>
							</div>
							<div>
								<p>Vision 100 IT offers a suite of tools, services and training to allow you to utilise IT as an effective tool for ministry. We work collaboratively with your staff or designated church member to develop a tailored website and package of tools to keep your newcomers informed and your ministry teams connected. We provide assistance and training in best practices for tools you already use, and are open to exploring ways to combine your current approach and applications into our ecosystem.</p>
								<p>"That's great! But who are you?" we hear you ask.</p>
							</div>
						</section>
					</div>
				</div>
				<div className="featured-second featured-dark" id="who">
					<div className="site-wrapper site-wrapper-padding">
						<header hidden>
							<h2>Who are Vision 100 IT?</h2>
						</header>
						<section>
							<p>We’re a team of passionate IT and web development engineers, ministry leaders and management professionals who voluntarily build, maintain, train and educate our clients in IT systems on the basis of years of collective knowledge gleaned from within the IT industry.</p>

							<p>Vision 100 IT has now existed for over a decade, and has gradually built up a knowledge base of best practices and approaches for doing church IT
								<i>sustainably</i>. We are all about getting
								<em>and keeping</em>
								our clients on the web, in order to more effectively reach the lost and minister to the people in their congregations.</p>
							<p>
								<h3>
									<a href="#">Meet the team.</a>
								</h3>
							</p>
						</section>
					</div>
				</div>
				<div className="featured-third featured-light" id="tools">
					<div className="site-wrapper site-wrapper-padding">
						<header>
							<h2>Tools + Philosophy</h2>
						</header>
						<section>
							<div className="text-slab">
								<em>The core product of Vision 100 IT isn't just a website or a CMS - it's a philosophy</em>
							</div>
							<p>There are plenty of products and approaches out there that you can use to get your church on the Web - our main aim is to help you to do this as best as possible.</p>
							<p>As a result we've collated a suite of supported tools that best help us to help you do IT well.</p>
							<p>We're eager to ensure that you're equipped to make the most of these tools as the web evolves over time. We won't just build you a website, but we'll coach you through keeping it up to date, provide ongoing support as your team members change, and walk you through new features and updates as they occur.</p>
						</section>
						<section>
							<div className="text-block-4">
								<header>
									<h3>Websites</h3>
								</header>
								<section>
									<ul>
										<li>Our websites are Responsive - they support smartphones and tablets</li>
										<li>They are built on Drupal CMS - a modern, powerful and secure platform, easily updated, supports user permissions</li>
										<li>We'll manage your Domain Name - you'll never need to worry about renewing or remembering your password every 3 years</li>
										<li>Modular features - features developed for one client become available for all clients</li>
										<li>Running on one of the worlds largest server platforms - uptime and server stability is nothing to worry about</li>
									</ul>
								</section>
							</div>
							<div className="text-block-4">
								<header>
									<h3>Administration</h3>
								</header>
								<section>
									<ul>
										<li>Flexible mailing lists for all your church-wide and team communications</li>
										<li></li>
									</ul>
								</section>
							</div>
							<div className="text-block-4">
								<header>
									<h3>Document management</h3>
								</header>
								<section>
									<ul>
										<li>Privately hosted document management platform</li>
										<li>Securely stored, not in the control of Dropbox or Google</li>
										<li>Conflicts easily managed so nothing gets lost</li>
										<li>Folder and file level user permissions</li>
										<li>Integrated into your website</li>
										<li></li>
									</ul>
								</section>
							</div>
							<div className="text-block-4">
								<header>
									<h3>Syndication tools</h3>
								</header>
								<section>
									<ul>
										<li>Podcasting</li>
										<li>Newsletter distribution</li>
									</ul>
								</section>
							</div>
						</section>
						<section>
							<p>Although we think this ecosystem is fantastic, and we've selected our tools on the basis of our years of experience, your needs may vary. If you're already have some solutions sorted, no problem! We'll work with you as best as we can to ensure you're being as effective as possible.</p>
						</section>
					</div>
				</div>
				<div className="featured-fourth featured-dark" id="events">
					<div className="site-wrapper site-wrapper-padding">
						<header>
							<h2>Events + Training</h2>
						</header>
						<section>
							<div>
								<div className="text-slab">
									<em>At the heart of Vision 100 IT is our events and training</em>
								</div>
							</div>
						</section>
					</div>
				</div>
				<div className="featured-fifth featured-light" id="pricing">
					<div className="site-wrapper site-wrapper-padding">
						<header>
							<h2>Pricing</h2>
						</header>
						<section>
							<div className="text-slab">
								<em>We know the best things in life are free</em>
							</div>
							<p>So we know you clicked 'Pricing' first, so we'll get it out of the way. We've given you a 'top' link to help you find your way back to the start.</p>
							<p>For our core features and services, we won't invoice you at all. Not in a "free tier" and send you five emails a day about how awesome "premium" is sort of way, but in a "We're really eager for you to get the most out of your IT for the good of the Gospel" sort of way. How does that sound?</p>
							<p>This is our rationale:
								<blockquote>We want to focus on providing you
									<em>
										services and methodology</em>
									that will keep you
									<em>engaged with your IT</em>, rather than a product that you'll set aside. If giving our services to you for free achieves that goal, we'll do it.</blockquote>
							</p>
							<p>We do have some
								<em>services</em>
								that will carry a cost, but we think that if you've got the right people on the ground, and spend some time in our documentation, you'll be fine without it.</p>
							<p>One of our
								<em>products</em>
								does carry a cost as well, and that is our registration payment system. The majority of that is managing paypal's costs so we've kept it as minimal as possible</p>
							<a href="#top">Top</a>
						</section>
					</div>
				</div>
				<div className="featured-sixth featured-dark" id="join">
					<div className="site-wrapper site-wrapper-padding">
						<header>
							<h2>Come on board</h2>
						</header>
						<section>
							<div className="text-slab">
								<em>La la la la</em>
							</div>
							<p></p>
						</section>
					</div>
				</div>
			</main>
		);
	}
}
